### ISSUE TITLE
对比友盟的更新功能有哪些优势呢？

### ISSUE THREAD

**Issue by hippyk** [WVector/AppUpdate#1]

**Comment by ysmintor** [comment]
友盟更新已经下架了吧？快1年的事了

**Comment by hippyk** [comment]
@ysmintor 为啥下架啊，好久没关注了

**Comment by WVector** [comment]
下架了，后来我自己写的，逻辑和友盟差不多

**Comment by WVector** [comment]
有时间可以加个增量更新，wifi状态下静默下载。

**Comment by hippyk** [comment]
@WVector 知道为啥下架吗？

**Comment by WVector** [comment]
引用--
这个服务因为目前面临N多非技术的挑战，导致我们很难再从技术层面维护好这个服务:
**iOS:**

>  第三方自动更新服务已经被苹果官方严格禁止了，集成第三方自动更新服务(如友盟+自动更新)的App在审核阶段会被大概率的拒绝。苹果官方数次要求友盟及早把iOS平台的更新服务停掉。在iOS新版本的系统上，其实应用更新已经是默认的功能了，所以第三方更新功能作用就不大了，没有太多存在意义了。

**Android:** 

> 面临的问题比较多，比如应用市场(除了Google Play之外，国内也有越来越多的市场渠道会对集成友盟自动更新插件的App审核拒绝)、部分系统厂商的限制(系统厂商可能会禁止掉非系统的更新，导致友盟更新组件报错或者抛异常)以及部分运营商的拦截(我们的下载CDN链接在某些地区的运营商会被禁止访问)，甚至APK的存储服务还会面临政策上的风险。

**Comment by hippyk** [comment]
@WVector 这些市场真小气
