### ISSUE TITLE
请问有没有类似网易云音乐那样的效果

### ISSUE THREAD

**Issue by xiuhaoli** [WVector/AppUpdate#11]
不用点升级，直接后台下载，下载完之后会弹出提示安装的dialog

**Comment by WVector** [comment]
目前没有，下次我加这个功能

**Comment by xiuhaoli** [comment]
好的，另外再问一个问题，我这边点击升级的按钮之后，页面会处于假死状态，点击任何地方都没反应，只有在下载完之后才会恢复正常，下面是我调用的代码，几乎没怎么变的从demo里复制过来的...
private void checkUpdate() {
        new UpdateAppManager.Builder()
                .setActivity(MainActivity.this)
                .setHttpManager(new UpdateAppHttpUtil())
                .setPost(true)
                //更新地址
                .setUpdateUrl(UrlUtil.obtainUserCheckUpdatePostUrl())
                //添加自定义参数
                .setParams(UrlUtil.getUserCheckUpdateParams(SystemUtil.getVersion()))
                //设置点击升级后，消失对话框
                .hideDialogOnDownloading(false)
//                .setTopPic(R.mipmap.top_4)
//                .setThemeColor(R.color.default_text_color)
                .build()
                .checkNewApp(new UpdateCallback() {
                    @Override
                    protected UpdateAppBean parseJson(String json) {
                        UpdateAppBean updateAppBean = new UpdateAppBean();
                        Res_CheckUpdateEntity entity = NetUtil.parseJson(json, Res_CheckUpdateEntity.class, MainActivity.this);
                        if (entity == null || "0".equals(entity.getData().getCode())) {
                            return updateAppBean.setUpdate("No");
                        }
                        Res_ApkInfo res_apkInfo = entity.getData().getInfo().getApk();
                        String update_log = "";// 为更新日志换行
                        for (String s : res_apkInfo.getUpdate_log()) {
                            update_log += s;
                            update_log += "\n";
                        }
                        updateAppBean
                                .setUpdate("Yes")                           // 是否更新Yes,No
                                .setNewVersion(res_apkInfo.getVersion())    // 新版本号
                                .setApkFileUrl(res_apkInfo.getUrl())        // 下载地址
                                .setTargetSize(res_apkInfo.getSize())       // 大小
                                .setUpdateLog(update_log)                   // 更新日志
                                .setConstraint(false);                      // 是否强制更新
                        return updateAppBean;
                    }

                    @Override
                    public void hasNewApp(UpdateAppBean updateApp, UpdateAppManager updateAppManager) {
                        updateAppManager.showDialog();
                    }

                    @Override
                    public void onBefore() {
                    }

                    @Override
                    public void onAfter() {
                    }

                    @Override
                    public void noNewApp() {

                    }

                });
    }

**Comment by xiuhaoli** [comment]
好的，另外再问一个问题，我这边点击升级的按钮之后，页面会处于假死状态，点击任何地方都没反应，只有在下载完之后才会恢复正常，下面是我调用的代码，几乎没怎么变的从demo里复制过来的...
`private void checkUpdate() {
        new UpdateAppManager.Builder()
                .setActivity(MainActivity.this)
                .setHttpManager(new UpdateAppHttpUtil())
                .setPost(true)
                //更新地址
                .setUpdateUrl(UrlUtil.obtainUserCheckUpdatePostUrl())
                //添加自定义参数
                .setParams(UrlUtil.getUserCheckUpdateParams(SystemUtil.getVersion()))
                //设置点击升级后，消失对话框
                .hideDialogOnDownloading(false)
//                .setTopPic(R.mipmap.top_4)
//                .setThemeColor(R.color.default_text_color)
                .build()
                .checkNewApp(new UpdateCallback() {
                    @Override
                    protected UpdateAppBean parseJson(String json) {
                        UpdateAppBean updateAppBean = new UpdateAppBean();
                        Res_CheckUpdateEntity entity = NetUtil.parseJson(json, Res_CheckUpdateEntity.class, MainActivity.this);
                        if (entity == null || "0".equals(entity.getData().getCode())) {
                            return updateAppBean.setUpdate("No");
                        }
                        Res_ApkInfo res_apkInfo = entity.getData().getInfo().getApk();
                        String update_log = "";// 为更新日志换行
                        for (String s : res_apkInfo.getUpdate_log()) {
                            update_log += s;
                            update_log += "\n";
                        }
                        updateAppBean
                                .setUpdate("Yes")                           // 是否更新Yes,No
                                .setNewVersion(res_apkInfo.getVersion())    // 新版本号
                                .setApkFileUrl(res_apkInfo.getUrl())        // 下载地址
                                .setTargetSize(res_apkInfo.getSize())       // 大小
                                .setUpdateLog(update_log)                   // 更新日志
                                .setConstraint(false);                      // 是否强制更新
                        return updateAppBean;
                    }

                    @Override
                    public void hasNewApp(UpdateAppBean updateApp, UpdateAppManager updateAppManager) {
                        updateAppManager.showDialog();
                    }

                    @Override
                    public void onBefore() {
                    }

                    @Override
                    public void onAfter() {
                    }

                    @Override
                    public void noNewApp() {

                    }

                });
    }`

**Comment by WVector** [comment]
.hideDialogOnDownloading(false) 因为你设置flase 所以会显示进度对话框，你是指点击 x 关闭后，点击自己的其他功能没法应？详细描述一下

**Comment by xiuhaoli** [comment]
点击返回键，dialog消失后点击应用的其他功能没反应，我把.hideDialogOnDownloading()设为true也是一样，dialog消失后点击其他没反应

**Comment by xiuhaoli** [comment]
只有在下载完毕之后会恢复正常，另外我在页面假死的时候比如说点击了跳转某个页面的按钮，等到下载完毕之后才跳转过去，响应被延迟了

**Comment by WVector** [comment]
我猜应该，出现在实现下载接口的问题，
callback.onProgress(progress, total);
这个方法调用过于频繁，你先最好自己判断一下，progress 0.01 - 0.02 再去回调，

**Comment by WVector** [comment]
每隔0.01回调一下

**Comment by xiuhaoli** [comment]
好的，我试试先

**Comment by WVector** [comment]
下次我在内部处理

**Comment by xiuhaoli** [comment]
确实是这个问题，我每隔0.05回调一次，现在已经不会卡死
