### ISSUE TITLE
提个建议

### ISSUE THREAD

**Issue by PiPiCaptain** [WVector/AppUpdate#12]
检查是否有新版本的功能，是不是没必要做在类库里？类库只需要提示框、下载、安装这些功能就好

**Comment by WVector** [comment]
建议很好，但是为了照顾两种极端，只能这样了，有人想一行代码完成版本更新，有人想只是利用下载功能，等等。

**Comment by PiPiCaptain** [comment]
@WVector 我下载下来，稍微修改了一下。把检查是否有新版本的功能去掉了
