### ISSUE TITLE
该框架不能处理下载地址重定向的问题！

### ISSUE THREAD

**Issue by yigepang** [WVector/AppUpdate#15]
贴个重定向后才是下载地址的网址：http://openbox.mobilem.360.cn/index/d/sid/3282847

**Comment by WVector** [comment]
v3.3.3已修复，谢谢反馈

**Comment by ahmerafzal1** [comment]
Please close issue after correction, after closing we as user help to knowing real known issue. Thanks this is just a suggestion.
