### ISSUE TITLE
用夜神模拟器运行会有问题.

### ISSUE THREAD

**Issue by AndroidFlyMing** [WVector/AppUpdate#16]
Didn't find class "com.vector.update_app.UpdateFileProvider" on path: DexPathList[[zip file "/data/app/com.pancool.ymi-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.pancool.ymi-2, /system/lib]]

**Comment by WVector** [comment]
真机正常？

**Comment by AndroidFlyMing** [comment]
真机正常,用模拟器跑就会报找不到com.vector.update_app.UpdateFileProvider类

**Comment by AndroidFlyMing** [comment]
你那边用模拟器跑有没有这种情况,好不好改?

**Comment by WVector** [comment]
genymotion没有问题

**Comment by WVector** [comment]
android studio 模拟器也正常

**Comment by AndroidFlyMing** [comment]
我是以compile的方式添加的,编译的时候就会报Didn't find class "com.vector.update_app.UpdateFileProvider" on path: DexPathList[[zip file "/data/app/com.pancool.ymi-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.pancool.ymi-2, /system/lib]],lib下找不到,夜神和51模拟器上报错

**Comment by WVector** [comment]
在模拟器上跑 版本更新 demo报错吗

**Comment by WVector** [comment]
1964414877 我的qq
