### ISSUE TITLE
日志显示下载成功，但界面提示“更新新版本出错，未知异常 code=200”

### ISSUE THREAD

**Issue by alonxiong** [WVector/AppUpdate#18]
打印出来的日志显示成功，但界面提示“更新新版本出错，未知异常 code=200”
日志如下(为了防止攻击，我在http:// 后面加了空格)：
08-08 14:10:22.169 20642-20698/? I/okHttp: <-- 200 OK http:// 3a3g.cn/app-1.1.apk (23ms）
08-08 14:10:22.169 20642-20698/? I/okHttp: 	Date: Tue, 08 Aug 2017 06:10:13 GMT
08-08 14:10:22.169 20642-20698/? I/okHttp: 	Server: Apache/2.4.25 (Win64) PHP/5.6.30
08-08 14:10:22.169 20642-20698/? I/okHttp: 	Accept-Ranges: bytes
08-08 14:10:22.169 20642-20698/? I/okHttp: 	ETag: W/"2355487-1502168009865"
08-08 14:10:22.169 20642-20698/? I/okHttp: 	Last-Modified: Tue, 08 Aug 2017 04:53:29 GMT
08-08 14:10:22.169 20642-20698/? I/okHttp: 	Content-Type: application/vnd.android.package-archive
08-08 14:10:22.169 20642-20698/? I/okHttp: 	Content-Length: 2355487
08-08 14:10:22.169 20642-20698/? I/okHttp: 	Keep-Alive: timeout=5, max=99
08-08 14:10:22.169 20642-20698/? I/okHttp: 	Connection: Keep-Alive
08-08 14:10:22.169 20642-20698/? I/okHttp:  
08-08 14:10:22.170 20642-20698/? I/okHttp: 	body: maybe [file part] , too large too print , ignored!
08-08 14:10:22.170 20642-20698/? I/okHttp: <-- END HTTP

**Comment by WVector** [comment]
你可以自己实现HttpManager接口，实现下载，自己去控制

**Comment by alonxiong** [comment]
是因为写存储权限的问题，现在已解决了，不过还是谢谢@WVector回复这么及时
另外，我发现会下载很多kotlin的文件，我现在用不到kotlin，怎么样可以关闭下载，这样我的项目没那么大，谢谢

**Comment by WVector** [comment]
删掉就可以

**Comment by alonxiong** [comment]
不行，删除后编译又会重新产生kotlin-stdlib开头的文件，然后在编译的classes.zip中也有kotlin的库

**Comment by WVector** [comment]
你可以不用demo，自己粘有用的。

**Comment by alonxiong** [comment]
我没有用demo，我在我的项目中只是增加了
compile 'com.qianwen:update-app:3.3.3'
compile 'com.qianwen:okhttp-utils:3.8.0'

**Comment by alonxiong** [comment]
我看了你的源代码，是不是你的源代码中有update-app-kotlin这个项目的缘故？

**Comment by WVector** [comment]
去掉那个，

**Comment by WVector** [comment]
compile 'com.qianwen:update-app:3.3.3'

**Comment by alonxiong** [comment]
不要compile 'com.qianwen:update-app:3.3.3'这个怎么行
编译肯定通不过啊
报UpdateAppManager找不到

**Comment by herodongliang** [comment]
我这点击升级之后，三星手机出现“更新新版本出错，异常”，跟你的问题一样吗？是权限问题吗？

**Comment by alonxiong** [comment]
你的手机是android什么版本的？

**Comment by herodongliang** [comment]
安卓6.0的啊，实在搞不懂怎么回事了，就三星有问题

**Comment by travelgeezer** [comment]
同样出现此问题， 原因是sd卡不存在。
解决办法：
1. 检测 sd 卡是否存， 不存在使用内部存储。
2. 安装时会出现解析错误。 需要文件修改权限后才可正常安装。（修改权限两种方法：一种是写入的时候指定。二是： 通过 ） `Runtime.getRuntime()exec(shell command)` 修改文件的权限。 
[我的解决办法](https://github.com/travelgeezer/react-native-android-update/commit/20e2781cb0e4f3b2f8814f8aa61294978c8202eb)
