### ISSUE TITLE
静默下载  问题  demo

### ISSUE THREAD

**Issue by momoc** [WVector/AppUpdate#21]
静默下载，关闭更新弹窗     再点击更新   一直显示  “app正在更新”  DownloadService.isRunning一直 true

**Comment by momoc** [comment]
如果只下载一半  把app关闭掉     状态栏下载进度   没有关闭

**Comment by WVector** [comment]
3.3.5已修复

**Comment by momoc** [comment]
如果只下载一半 把app关闭掉 状态栏下载进度 没有关闭
