### ISSUE TITLE
下载路径错误:/storage/C33C-1BF6/Download

### ISSUE THREAD

**Issue by NewBrandSTONE** [WVector/AppUpdate#26]
千匍，您好

  最近在使用您开发的升级库遇到一点小问题，在测试的时候，我使用的是

  华为Che1-CL10的手机

- 系统EMUI4.0
- Android版本6.0.1

点击更新APP（默认），就是最简单的更新按钮，控制台提示
 - 下载路径错误:/storage/C33C-1BF6/Download

我看了一下您的代码，在UpdateAppManager.java中，第140行的verify()函数

有一个preSuffix验证，限定了下载路径必须是要以"/storage/emulated"开头的

这里修改一下会不会好一些，

通过判断是否装载了SD卡会不会好一些，否则有些手机就没法下载了。

**Comment by WVector** [comment]
不好意思，没考虑全，3.3.6 我去掉对前缀的校验。

**Comment by NewBrandSTONE** [comment]
谢谢，期待ing~
