### ISSUE TITLE
每次弹出都先显示默认的红色背景

### ISSUE THREAD

**Issue by bean-liu** [WVector/AppUpdate#27]
谢谢开源这个好用的库，发现一个小问题，设置的背景图片之后，弹出升级提示的背景经常能看到由默认的红色背景变成我设置的那个背景

**Comment by WVector** [comment]
根据你的描述我不能确定是啥造成的，的sample也出现这种问题吗？

**Comment by WVector** [comment]
根据你的描述我不能确定是啥造成的，样例sample也出现这种问题吗？

**Comment by bean-liu** [comment]
换了新版之后没有，估计应该是之前的那个版本的自动提色导致的背景图片替换不流畅
