### ISSUE TITLE
三星手机自定义接口 每次都出现更新新版本出错，异常！怎么回事？

### ISSUE THREAD

**Issue by herodongliang** [WVector/AppUpdate#29]
小米偶尔会出这个问题 我自己的OPPO没出现这个问题 请教一下 怎么解决？

**Comment by WVector** [comment]
你使用的网络框架是？

**Comment by herodongliang** [comment]
OkGo.<String>get(url).params(params).execute(new com.lzy.okgo.callback.StringCallback() {
            @Override
            public void onSuccess(com.lzy.okgo.model.Response<String> response) {
                callBack.onResponse(response.body());
            }

            @Override
            public void onError(com.lzy.okgo.model.Response<String> response) {
                super.onError(response);
                callBack.onError("异常");
            }
        });

OkGo.<File>get(url).execute(new com.lzy.okgo.callback.FileCallback(path, fileName) {
            @Override
            public void onSuccess(com.lzy.okgo.model.Response<File> response) {
                callback.onResponse(response.body());
            }

            @Override
            public void onStart(com.lzy.okgo.request.base.Request<File, ? extends com.lzy.okgo.request.base.Request> request) {
                super.onStart(request);
                callback.onBefore();
            }

            @Override
            public void onError(com.lzy.okgo.model.Response<File> response) {
                super.onError(response);
                callback.onError("异常");
            }

            @Override
            public void downloadProgress(Progress progress) {
                super.downloadProgress(progress);
                callback.onProgress(progress.fraction, progress.totalSize);
            }
        });

就是你的demo上的，跟这个有关系吗？

**Comment by herodongliang** [comment]
我看网上说可能是因为文件存储路径和权限的问题 但具体的解决方案不是很清楚，报的错在DownloadService下的
@Override
        public void onError(String error) {
            Toast.makeText(DownloadService.this, "更新新版本出错，" + error, Toast.LENGTH_SHORT).show();
            //App前台运行
            if (mCallBack != null) {
                mCallBack.onError(error);
            }
            try {
                mNotificationManager.cancel(NOTIFY_ID);
                close();
            } catch (Exception e1) {
                e1.printStackTrace();
            }
        }
希望您能帮忙解决一下，急死了 ,谢谢

**Comment by WVector** [comment]
应该没有访问外部空间权限，你先了解一下android 权限管理机制。
