### ISSUE TITLE
本地客户端版本号与服务器版本号一样都是0.8.3，但还是会提示更新

### ISSUE THREAD

**Issue by xiaoniu** [WVector/AppUpdate#32]
部署服务器后台的代码后，找不到mobileVersionManger/login.html

然后拿sample里的url测试，发现sample里的url只是指向了github里更新的json文件，不管本地版本号是多少，都会返回此json文件并更新。

请求：
OkGo: --> GET https://raw.githubusercontent.com/WVector/AppUpdateDemo/master/json/json.txt?key2=value3&appKey=ab55ce55Ac4bcP408cPb8c1Aaeac179c5f6f&appVersion=0.8.3&key1=value2 http/1.1

返回：
OkGo: 	body:{
                                                                "update": "Yes",
                                                                "new_version": "0.8.3",
                                                                "apk_file_url": "https://raw.githubusercontent.com/WVector/AppUpdateDemo/master/apk/app-debug.apk",
                                                                "update_log": "1，添加删除信用卡接口。\r\n2，添加vip认证。\r\n3，区分自定义消费，一个小时不限制。\r\n4，添加放弃任务接口，小时内不生成。\r\n5，消费任务手动生成。",
                                                                "target_size": "5M",
                                                                "new_md5":"295687E756F569C7159974DD493489A5",
                                                                "constraint": false
                                                              }

正常：
{
  "update": "No",//没有新版本
}

**Comment by WVector** [comment]
sample 中url只是为了演示。

**Comment by xiaoniu** [comment]
这个是了解的，主要表达的还是第一句
** 部署服务器后台的代码后，找不到mobileVersionManger/login.html **
因为不能测试自己的后台，才会用sample里的url

**Comment by qq781548819** [comment]
有个业务，选择强制更新，或者普通更新，除了使用update字段判断是否弹出更新对话框，能不能再添加一个判断规则，如果本地客户端当前版本跟new_version字段提供的版本一致后，不再弹出对话框，因为这样表示改用户的客户端版本一句更新到最新版

**Comment by qq781548819** [comment]
有个业务，选择强制更新，或者普通更新，除了使用update字段判断是否弹出更新对话框，能不能再添加一个判断规则，如果本地客户端当前版本跟new_version字段提供的版本一致后，不再弹出对话框，因为这样表示该用户的客户端版本已经更新到最新版，感谢作者无私奉献
