### ISSUE TITLE
为什么会一直显示都有更新升级

### ISSUE THREAD

**Issue by chenxiaofei910714** [WVector/AppUpdate#60]
versionwo改成1.5.3几了，为什么还是显示有新版本下载更新吗？服务器的版本0.8.3，怎么还可以一直提示有版本更新呢

**Comment by WVector** [comment]
这个版本更新是根据服务器返回的json

`{
  **"update": "Yes",**
  "new_version": "0.8.3",
  "apk_file_url": "https://raw.githubusercontent.com/WVector/AppUpdateDemo/master/apk/app-debug.apk",
  "update_log": "1，添加删除信用卡接口。\r\n2，添加vip认证。\r\n3，区分自定义消费，一个小时不限制。\r\n4，添加放弃任务接口，小时内不生成。\r\n5，消费任务手动生成。",
  "target_size": "5M",
  "new_md5":"E14F1641C7829D7B387F2C8227011EBA",
  "constraint": false
}`
中update字段控制的
