### ISSUE TITLE
强制更新有何意义？对话框还是可以按返回键关闭掉

### ISSUE THREAD

**Issue by RuanJH** [WVector/AppUpdate#7]
虽然隐藏了关闭按钮，但是返回键还是可以关闭对话框

**Comment by WVector** [comment]
强制更新对话框关不掉吧，直接退出了app

**Comment by WVector** [comment]
这样app不更新就用不了了

**Comment by RuanJH** [comment]
你自己试下，强制更新，按下返回键试下看看能不能关闭，我这边是可以关闭对话框的。还有，通知栏点击没事件，也不能取消当前的更新操作

**Comment by WVector** [comment]
1，我测试了，点击返回键直接退出了app,。
2，点击通知不能取消本身就没有开发。

**Comment by WVector** [comment]
看到的并不是一个对话框，而是一个Acitivtiy。

**Comment by WVector** [comment]
有啥好的建议欢迎提出。

**Comment by RuanJH** [comment]
1、点击返回的时候，直接退出就直接重新进来了。不是完全退出来吧？
2、退出的时候，服务是停止了，但是通知栏清除不掉，也没办法可以移除掉。
3、建议做取消更新操作。

**Comment by WVector** [comment]
我修改强制更新策略：点击返回键直接返回桌面

**Comment by RuanJH** [comment]
加你QQ了，通过一下

**Comment by hlla** [comment]
@RuanJH 你想demo有强制更新,你得修改下UpdateAppBean类中isConstraint()方法的返回值呀
