### ISSUE TITLE
下载中 页面滑动卡顿

### ISSUE THREAD

**Issue by lizilindea** [WVector/AppUpdate#9]
在下载过程中 是否能关闭dialog   让在后台下载

我修改了源码 在下载中 关闭dialog   但是在下载中的时候  页面滑动非常卡顿 不知道为什么

**Comment by WVector** [comment]
给我看一下你改的代码

**Comment by WVector** [comment]
V3.2.7 可以设置 点击升级后自定关闭对话框

**Comment by lizilindea** [comment]
那我换下最新的代码 我用的之前下载的  你今天好像更新了
